from definitions.date_standards import EVEN_DAYS
from definitions.processable_entities import Dataset, Derivative

SCHEDULE = [Dataset("united-kingdom",
                    data_dir="subnational/united-kingdom/cases"),
            Dataset("united-kingdom-deaths",
                    data_dir="subnational/united-kingdom/deaths"),
            Dataset("united-kingdom-admissions",
                    data_dir="subnational/united-kingdom/admissions"),
            Dataset("united-kingdom-local",
                    data_dir="subnational/united-kingdom-local/cases",
                    max_wall_clock_minutes=24*60),
            Dataset("united-kingdom-local-deaths",
                    data_dir="subnational/united-kingdom-local/deaths",
                    max_wall_clock_minutes=24*60),
            Dataset("united-kingdom-local-admissions",
                    data_dir="subnational/united-kingdom-local/admissions",
                    max_wall_clock_minutes=24*60),
            Dataset("united-states",
                    data_dir="subnational/united-states/cases"),
            Dataset("regional-cases", data_dir="region/cases"),
            Dataset("regional-deaths", data_dir="region/deaths"),
            Dataset("cases", data_dir="national/cases"),
            Dataset("deaths", data_dir="national/deaths"),
            Dataset("belgium", data_dir="subnational/belgium/cases"),
            Dataset("brazil", data_dir="subnational/brazil/cases"),
            Dataset("canada", data_dir="subnational/canada/cases"),
            Dataset("colombia", data_dir="subnational/colombia/cases"),
            Dataset("germany", data_dir="subnational/germany/cases"),
            Dataset("india", data_dir="subnational/india/cases"),
            Dataset("italy", data_dir="subnational/italy/cases"),
            Dataset("south-africa", data_dir="subnational/south-africa/cases"),
            Dataset("south-africa-deaths", data_dir="subnational/south-africa/deaths"),
            Dataset("vietnam", data_dir="subnational/vietnam/cases"),
            Derivative("united-kingdom-collated",
                       data_dir="subnational/united-kingdom/collated",
                       dependencies=["united-kingdom",
                                     "united-kingdom-deaths",
                                     "united-kingdom-admissions"]),
            Dataset("united-kingdom-full",
                    data_dir="subnational/united-kingdom/cases-all-time",
                    max_wall_clock_minutes=7*24*60
                    timeout=3*24*60*60,
                    frequency=[23]),
            Dataset("united-kingdom-deaths-full",
                    data_dir="subnational/united-kingdom/deaths-all-time",
                    max_wall_clock_minutes=7*24*60
                    timeout=3*24*60*60,
                    frequency=[23]),
            Dataset("united-kingdom-admissions-full",
                    data_dir="subnational/united-kingdom/admissions-all-time",
                    max_wall_clock_minutes=7*24*60
                    timeout=3*24*60*60,
                    frequency=[23]),
            Dataset("united-kingdom-local-full",
                    data_dir="subnational/united-kingdom-local/cases-all-time",
                    max_wall_clock_minutes=7*24*60
                    timeout=3*24*60*60,
                    frequency=[14]),
            Dataset("united-kingdom-local-deaths-full",
                    data_dir="subnational/united-kingdom-local/deaths-all-time",
                    max_wall_clock_minutes=7*24*60
                    timeout=3*24*60*60,
                    frequency=[14]),
            Dataset("united-kingdom-local-admissions-full",
                    data_dir="subnational/united-kingdom-local/admissions-all-time",
                    max_wall_clock_minutes=7*24*60
                    timeout=3*24*60*60,
                    frequency=[14]),
            Dataset("united-states-full",
                    data_dir="subnational/united-states/cases-all-time",
                    max_wall_clock_minutes=7*24*60,
                    timeout=3*24*60*60,
                    frequency=[27]),
            Dataset("regional-cases-full", data_dir="region/cases-all-time",
                    max_wall_clock_minutes=7*24*60,
                    timeout=3*24*60*60,
                    frequency=[9]),
            Dataset("regional-deaths-full", data_dir="region/deaths-all-time",
                    max_wall_clock_minutes=7*24*60,
                    timeout=3*24*60*60,
                    frequency=[13]),
            Dataset("cases-full", data_dir="national/cases-all-time",
                    max_wall_clock_minutes=7*24*60,
                    timeout=3*24*60*60,
                    frequency=[1]),
            Dataset("deaths-full", data_dir="national/deaths-all-time",
                    max_wall_clock_minutes=7*24*60,
                    timeout=3*24*60*60,
                    frequency=[4]),
            Dataset("belgium-full", data_dir="subnational/belgium/cases-all-time",
                    max_wall_clock_minutes=7*24*60,
                    timeout=3*24*60*60,
                    frequency=[20]),
            Dataset("brazil-full", data_dir="subnational/brazil/cases-all-time",
                    max_wall_clock_minutes=7*24*60,
                    timeout=3*24*60*60,
                    frequency=[21]),
            Dataset("canada-full", data_dir="subnational/canada/cases-all-time",
                    max_wall_clock_minutes=7*24*60,
                    timeout=3*24*60*60,
                    frequency=[3]),
            Dataset("colombia-full", data_dir="subnational/colombia/cases-all-time",
                    max_wall_clock_minutes=7*24*60,
                    timeout=3*24*60*60,
                    frequency=[10]),
            Dataset("germany-full", data_dir="subnational/germany/cases-all-time",
                    max_wall_clock_minutes=7*24*60,
                    timeout=3*24*60*60,
                    frequency=[6]),
            Dataset("india-full", data_dir="subnational/india/cases-all-time",
                    max_wall_clock_minutes=7*24*60,
                    timeout=3*24*60*60,
                    frequency=[25]),
            Dataset("italy-full", data_dir="subnational/italy/cases-all-time",
                    max_wall_clock_minutes=7*24*60,
                    timeout=3*24*60*60,
                    frequency=[7]),
            Dataset("south-africa-full", data_dir="subnational/south-africa/cases-all-time",
                    max_wall_clock_minutes=7*24*60,
                    timeout=3*24*60*60,
                    frequency=[11]),
            Dataset("south-africa-deaths-full", data_dir="subnational/south-africa/deaths-all-time",
                    max_wall_clock_minutes=7*24*60,
                    timeout=3*24*60*60,
                    frequency=[11]),
            Dataset("vietnam-full", data_dir="subnational/vietnam/cases-all-time",
                    max_wall_clock_minutes=7*24*60,
                    timeout=3*24*60*60,
                    frequency=[12]),
            Derivative("united-kingdom-collated-full",
                       data_dir="subnational/united-kingdom/collated-all-time",
                       dependencies=["united-kingdom-full",
                                     "united-kingdom-deaths-full",
                                     "united-kingdom-admissions-full"],
                       max_wall_clock_minutes=60,
                       frequency=[23])
            ]
